(define (problem puzzles_problem)
    (:domain puzzles)
    (:objects 
        c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 - cell
        p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 - puzzle
    )
    (:init
        (not (empty c1)) (not (empty c2)) (not (empty c3)) (not (empty c4))
        (not (empty c5)) (not (empty c6)) (not (empty c7)) (not (empty c8)) 
        (not (empty c9)) (not (empty c10)) (not (empty c11)) (not (empty c12))
        (not (empty c13)) (not (empty c14)) (not (empty c15)) (empty c16)
        (at c1 p15) (at c2 p2) (at c3 p1) (at c4 p12) 
        (at c5 p8) (at c6 p5) (at c7 p6) (at c8 p11)
        (at c9 p4) (at c10 p9) (at c11 p10) (at c12 p7)
        (at c13 p3) (at c14 p14) (at c15 p13)
        (near c1 c2) (near c1 c5)
        (near c2 c1) (near c2 c6) (near c2 c3)
        (near c3 c2) (near c3 c7) (near c2 c4)
        (near c4 c3) (near c4 c8)
        (near c5 c1) (near c5 c6) (near c5 c9)
        (near c6 c5) (near c6 c2) (near c6 c7) (near c6 c10)
        (near c7 c11) (near c7 c6) (near c7 c3) (near c7 c8)
        (near c8 c4) (near c8 c7) (near c8 c12)
        (near c9 c5) (near c9 c10) (near c9 c13)
        (near c10 c9) (near c10 c6) (near c10 c11) (near c10 c14)
        (near c11 c10) (near c11 c7) (near c11 c12) (near c11 c15)
        (near c13 c9) (near c13 c14)
        (near c14 c13) (near c14 c10) (near c14 c15)
        (near c15 c14) (near c15 c11) (near c15 c16)
        (near c16 c15) (near c16 c12)
    )
    (:goal
        (and 
            (at c1 p1)                                                                                                                         
            (at c2 p2)                                                                                                                         
            (at c3 p3)                                                                                                                         
            (at c4 p4)                                                                                                                         
            (at c5 p5)                                                                                                                         
            (at c6 p6)                                                                                                                         
            ;(at c7 p7)                                                                                                                         
            ;(at c8 p8)                                                                                                                         
            ;(at c9 p9)                                                                                                                         
            ;(at c10 p10)                                                                                                                       
            ;(at c11 p11)                                                                                                                       
            ;(at c12 p12)                                                                                                                       
            ;(at c13 p13)                                                                                                                       
            ;(at c14 p14)                                                                                                                       
            ;(at c15 p15)
        )
    )
)